name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      # Caching odvisnosti
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Namestitev odvisnosti
      - name: Namestitev odvisnosti
        run: npm install

      # Gradnja React aplikacije
      - name: Gradnja aplikacije
        run: npm run build

      # Artefakti â€“ shranimo build
      - name: Upload build artefakta
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      # Prenesi artefakt build-a
      - name: Download artefakt
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - name: Prijava v Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Gradnja Docker slike
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest

      - name: Push Docker slike
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v4

      - name: Prenesi build artefakt
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      - name: Namestitev Firebase CLI
        run: npm install -g firebase-tools

      - name: Nastavi Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy na Firebase Hosting
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}